spring:
  application:
    name: HomeRepAPIGateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**  # Проксируем все запросы к auth-service
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5  # Количество новых токенов в секунду (5 запросов/сек)
                redis-rate-limiter.burstCapacity: 10 # Максимальное накопление токенов (10)
                key-resolver: "#{@userKeyResolver}"   # Используем кастомный ключ (например, IP)

#        - id: user-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/users/**
#          filters:
#            - JwtAuthFilter  # Проверяем токен перед проксированием
#
#        - id: order-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/orders/**
#          filters:
#            - JwtAuthFilter  # Проверяем токен перед проксированием

server:
  port: 7099
