spring:
  application:
    name: HomeRepAPIGateway
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/homerep_gateway
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: homerep.orders.topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**  # Проксируем все запросы к auth-service
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5  # Количество новых токенов в секунду (5 запросов/сек)
                redis-rate-limiter.burstCapacity: 10 # Максимальное накопление токенов (10)
                key-resolver: "#{@userKeyResolver}"   # Используем кастомный ключ (например, IP)

#        - id: user-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/users/**
#          filters:
#            - JwtAuthFilter  # Проверяем токен перед проксированием
#
#        - id: order-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/orders/**
#          filters:
#            - JwtAuthFilter  # Проверяем токен перед проксированием

server:
  port: 7099
